# file-security 
xls=application/vnd.ms-excel,application/msexcel,application/x-excel
xlsx=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
xlsm=application/vnd.ms-excel.sheet.macroEnabled.12
doc=application/msword,application/vnd.ms-word
docx=application/vnd.openxmlformats-officedocument.wordprocessingml.document
ppt=application/vnd.ms-powerpoint,application/mspowerpoint,application/powerpoint
pptx=application/vnd.openxmlformats-officedocument.presentationml.presentation
pptm=application/vnd.ms-powerpoint.presentation.macroEnabled.12
ppsx=application/vnd.openxmlformats-officedocument.presentationml.slideshow
pdf=application/pdf
hwp=application/x-hwp,application/haansofthwp
txt=text/plain
csv=text/csv,text/plain
jpeg=image/jpeg,image/pjpeg
jpg=image/jpeg,image/pjpeg
jpe=image/jpeg
png=image/png,image/x-png
gif=image/gif
bmp=image/bmp,image/x-ms-bmp
tif=image/tiff
tiff=image/tiff
dwg=image/vnd.dwg,application/dwg,application/x-dwg
wav=audio/wav,audio/x-wav
mp3=audio/mpeg,audio/mp3
avi=video/avi,video/x-msvideo
mp4=video/mp4
asf=video/x-ms-asf,video/asf
flv=video/x-flv
wmv=video/x-ms-wmv
zip=application/zip,application/x-zip-compressed
msg=application/vnd.ms-outlook
xps=application/vnd.ms-xpsdocument
xdw=application/octet-stream
gul=application/octet-stream
enc=application/octet-stream
hdc=application/octet-stream