#HSO Web Service Client (Create Method Parameter)
CSR_WSDL_SERVICE = SO_OLM_CHANGE
CSR_WSDL_SERVICE_URL = http://ep.hanwha-solarone.com/

#LF SAP Link
LF_SAP_MAX_CONNECT = 100
LF_SAP_CLIENT_NO = 100
LF_SAP_USER_ID = IF_IDMS
LF_SAP_PASSWORD = ifadminidms0
LF_SAP_LANGUAGE = KO
LF_SAP_SERVER_IP = 165.244.231.68
LF_SAP_SYSTEM_NO = 00
LF_SAP_SYSTEM_ID = LFP_POS
LF_SAP_R3_NAME = LFP
LF_SAP_HOST_NAME = LGFLFPDB0
LF_SAP_SERVER_NAME = LGFERP_REAL
LF_SAP_POOL_NAME = SAP_POOL_NAME
LF_SAP_GROUP = LGFLFP

#LF WEP Link
LF_WEB_MDP_URL = http://10.49.8.194:9003/mdp/index.jsp
LF_WEB_PLM_URL = http://10.49.8.220:8080/enovia/servlet/lfcssologin		
				
#HANWHA 
HW_WSDL_SERVICE_URL = http://htg.circle.hanwha.com/ 
#HW_WSDL_SERVICE_URL = http://hanwha.eagleoffice.co.kr/
HW_COMPANY_ID = 503
HW_SYSTEM_ID = 503AP0028
HW_ADRM_WSDL_SERVICE_URL = http://96.97.23.66:8080/
HW_ADRM_WS_KEY = A1234 
HW_ADRM_SERVICE_CODE =  PRIME_001
HW_GROUPWARE_URL = http://htg.circle.hanwha.com/neo/branch/common/slo/goSloTarget.mvc?authType=2&destination=


#SKHynix Link
SK_MPM_URL = http://heps.skhynix.com/sso/agentless/agentless_redirect.jsp?initpage=http://mpm.skhynix.com/indexSK.jsp
#DEV  url=http://ssodev.skhynix.com/sso/agentless/agentless_redirect.jsp?initpage=http://mpmdev.skhynix.com/indexSK.jsp
# http://sso.skhynix.com/sso/agentless/agentless_redirect.jsp?initpage=http://mpm.skhynix.com/indexSK.jsp
SK_ACC_RJC_URL = http://ssodev.skhynix.com/common/OnAccessReject.htm 
SK_LOGOUT_URL = http://ssodev.skhynix.com/common/logout.asp?TARGET=http://10.156.20.117:8080/sso_login.jsp
FILE_UPLOAD_CTS_DIR = C://OLMFILE//cts//

#CJ Val
CJ_SSO_URL = http://dev.cjwise.net
#QA CJ_SSO_URL = http://qa.cjwise.net
#Run CJ_SSO_URL = http://cjwise.net
EMP_PHOTO_URL = https://ep.halla.com


#DAELIM
IEP_POP_URL = http://portal.daelimplant.com/ProjectPortal/UserControls/BestPractice/BestPracticeDetailView.aspx
DLM_WEBSERVICE_URL = http://172.20.101.23:8880/ifweb/services/DLMWebService?wsdl
DLM_GW_URL = https://gw.daelimcloud.com
DLM_PUSH_serverUrl =http://172.25.1.88:8180/mgw/rcv_register_message.ctl
DLM_PUSH_appId =com.covimdm.daelim.dev
DLM_PUSH_serviceCode =eClick
DLM_PUSH_sendsmsYn =Y
DLM_PUSH_senderCode =Superadmin
DLM_PUSH_senderName =eClick
DLM_PUSH_senderNum =0237048643

#DLM_PUSH_serverUrl =http://pushapi.daelimcloud.com:8180/mgw/rcv_register_message.ctl
#DLM_PUSHPUSH_appId =com.covimdm.daelim
#DLM_PUSHPUSH_serviceCode =ALL
#DLM_PUSHPUSH_sendsmsYn =N
#DLM_PUSHPUSH_senderCode =DCPSysAdmin
#DLM_PUSHPUSH_senderName =eClick
#DLM_PUSHPUSH_senderNum =0237048643

#DLM_GW_URL = https://gw.daelimcloud.com

#DAESANG
DS_ERP_URL = http://ep.erpd.daesang.com:50000/daesangSSO/sso.jsp

#CSI
CSI_HOST = dskorea.com
CSI_BASEDN = DC=dskorea,DC=com
CSI_LDAP = 203.228.108.2

#HYUNDAI HEC
lgySystemId = H-WAY
wfDocOpenJspUrl = /custom/hyundai/hec/wf/zhec_goWorkflow
wfViewAPIUrl = https://autowaywf.hyundai.net/HECWebService/ExternalWebService.asmx?wsdl
wfDocViewJspUrl = /custom/hyundai/hec/wf/zhec_goProcess
dftCompId = H139

#WISE NUT \uc778\uae30\uac80\uc0c9\uc5b4 API URL
#\uc6b4\uc601
#WISENUT_POPULAR_URL = http://10.224.1.151:7800/manager/WNRun.do?target=popword&collection=KPAL&range=W
#\uac1c\ubc1c 
WISENUT_POPULAR_URL = http://10.224.99.221:7800/manager/WNRun.do?target=popword&collection=KPAL&range=W 


#MANDO
#MND_SYS_KEY =58SYafe967-b9ed-48b6-8c9fa-a88f456f28c
#MND_PWD_KEY =356712568400906510087672
#MND_CONTENTS =CONTENTS.BPMS.SSO

#MANDO BROSE
MND_SYS_KEY = Wd12UYai12-ag79-00UI-09L56-f3703hdlv4du
MND_PWD_KEY = 357685418026927878907316
MND_CONTENTS = CONTENTS.MBCOBPMS.SSO

#SSG Val
SSG_SSO_URL = https://ssodev.emart.com:8443

#SKDC	
AIP_NAS = \\\\\\\\10.224.200.107\\\\aip\\\\ifd\\\\nonsap\\\\pal
#AIP_SVR_ADDR = https://apigw.skdiscovery.com
AIP_SYS_ID = 5FA347DF-4C0A-43EC-B90F-D6DB7BD4C40B
FILE_AIP_EXTENSION = DOCX,DOCM,DOC,DOTX,DOTM,DOT,XLSX,XLSM,XLSB,XLS,CVS,XLTX,XLT,XLAM,XLA,XPS,PPTX,PPTM,PPT,POTX,POTM,POT,PPSX,PPSM,PPA,PDF

#KDNVN
AIP_SVR_ADDR = https://cnrgateway.kdiwin.com
AIP_SERVICEKEY = 4ae20a70-0478-409c-b01e-3911164a89cc

#PAPAGO
PAPAGO_API_URL = http://localhost/
PAPAGO_TRANS_CLIENT_ID = x3jg825nyy
PAPAGO_TRANS_CLIENT_SECRET = 8TvMUZIyTD3Y8Vkha32L4MZJkIAhfKJEeCh7iIkd
PAPAGO_DECT_CLIENT_ID = 688fpkakfc
PAPAGO_DECT_CLIENT_SECRET = Z4m3t5L80t7T5blpdpao9dKpq7heKsR1Wrqn7bmm

#GPTAI
GPTAI_API_URL = http://sfolm.iptime.org:8000

#SK
SK_MAIL_SERVER = http://api.skinnovation.com/mail/service/sendMessage
SK_MAIL_TOKEN = Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJDb21tb25BUElzZXJ2aWNlMDAzQGRza2NvcnAubmV0IiwibGVnYWN5SWQiOiJHU0RNREVWIiwic2VydmljZUlkIjoiRDE0MTZBREMtOUZGNy00NTI2LUFCMzQtQ0U2MjVFNDJGNDU2IiwiYXBpSWQiOiJzZW5kTWVzc2FnZSIsInB1cnBvc2UiOiLtkZzspIDrrLjshJzqtIDrpqzsi5zsiqTthZwg66mU7J28IOuwnOyGoSDthYzsiqTtirjsmqkiLCJzZW5kQWNjb3VudElkIjoiY29tbW9uYXBpc2VydmljZTAwMyIsInNlbmRBY2NvdW50TWFpbCI6IkNvbW1vbkFQSXNlcnZpY2UwMDNAZHNrY29ycC5uZXQiLCJyZWdpc3RlckNyZWF0ZURUIjoiMjAyNC0xMS0xMyAxNTo0ODo0NSIsInRva2VuQ3JlYXRlRFQiOiIyMDI0LTExLTEzIDE2OjE3OjI3IiwicmVnaXN0ZXJVc2VySWQiOiJzaTc3NzcxIiwiYXV0aEhvc3RJbmZvIjoiW3tcImhvc3ROYW1lXCI6XCJza28tZ3NkbWRhbGwwMVwiLFwiaXBBZGRyZXNzXCI6XCIxMC44Mi40LjgzXCJ9LHtcImhvc3ROYW1lXCI6XCJza2ktdHZtLWIwNjBcIixcImlwQWRkcmVzc1wiOlwiMTAuOTAuNzAuNjBcIn1dIn0.-jy9HbC-OiEKcsIytMM_6zfZdHOvMogTvDB4lWsPiyg

#YOUNGONE 
YO_GW_VIEW_URL = https://gw.youngonedev.com
INTERNAL_SERVER_URL = http://weclick.daelim.co.kr:8090/


#IF API
OLM_API_KEY = 123123
OLM_API_FILE_UPLOAD_PATH = C://OLMFILE//BPLM//

#Timezone
SERVER_TIMEZONE = Asia/Seoul
KEY_COLUMNS_TIMEZONE = RegDate,RegDT, CompletionDT, ReqDueDate, DueDate, WORK_DATE, work_date, value, PlainText, StartTime, EndTime, CreationTime, reqdueDate, dueDate
DATE_COLUMNS_TIMEZONE = CompletionDT, ReqDueDate, DueDate, WORK_DATE, work_date, CreationTime, reqdueDate, dueDate
QUERY_METHOD_TIMEZONE = getESMSRInfo,getSRAttr,getESPSearchList_gridList,getESPSearchExcelList_gridList,getRoleRecord_gridList,getMemberRecord_gridList,selectMbrRcd_gridList,getSRAttrList,getSRAttr,getESMProLogInfo_gridList,espFile_gridList,insertSRAttr,insertSRAttrRev,updateESMSR,insertSRMst,insertOpsMbr,updateMbrRcd,insertActivityLog,espFile_insert,updateESMSRStatus,updateActivityLog,getindividualPerformanceReportGrid02Data_gridList

#DRM
DRM_KEY_ID =
DRM_SOFTCAMP_KEY = d:/softcamp/04_KeyFile/keyDAC_SVR0.sc
DRM_SOFTCAMP_MODULE_PATH = d:/softcamp/02_Module/02_ServiceLinker/softcamp.properties
DRM_DECODING_FILEPATH = C://OLMFILE//file//fsdinit

# FASOO
DRM_FASOO_KEY_ID =
DRM_FASOO_DECODING_FILEPATH = C://OLMFILE//file//fasoo//
DRM_FASOO_MODULE_PATH = C://fasoo//fsdinit
DRM_FASOO_SECURITY_CODE =

DOC_VIEW_DRM = Y
DRM_SOFTCAMP_DOWN_USE = N
DOC_DOWNLOAD_FASOO_YN = N

# MIP
DRM_MIP_API_URL =
DRM_MIP_API_KEY =
DRM_MIP_FILEPATH =
