WEBSSO_SSOSERVICE_URL = http://sso.skcorp.com/SSO/AuthWeb/WebServices/SSOService.asmx
WEBSSO_ENC_KEY = !ssoNetsConfigKey
SITESERVER_IP = 10.82.4.83
SITESERVER_DNS = gsdmdev.sk-on.com
SSO_PROVIDER_DOMAIN = sso.skcorp.com
SITESERVER_TIMEOUT = 5000
CLIENT_IP_CHECK_LEVEL = 0
DEFAULT_BUFFER_TIME = 0
SUBMITNEXTURL_OPTION = submit
SCRIPT_OPTION = top
SITE_ACCESS_DENIED_PAGE = https://gsdmdev.sk-on.com/custom/sk/loginAuth.do