rahonlog4j.rootLogger=debug, stdout, out
#rahonlog4j.rootLogger=info, stdout, out


rahonlog4j.logger.org.apache.activemq=INFO
rahonlog4j.logger.org.apache.activemq.spring=WARN
rahonlog4j.logger.org.apache.activemq.store.journal=INFO
rahonlog4j.logger.org.activeio.journal=INFO

# CONSOLE appender not used by default
rahonlog4j.appender.stdout=com.rathontech.common.logger.ConsoleAppender
rahonlog4j.appender.stdout.layout=com.rathontech.common.logger.PatternLayout
rahonlog4j.appender.stdout.layout.ConversionPattern=%d [%-15.15t] %-5p %-30.30c{1} - %m%n

# File appender
rahonlog4j.appender.out=com.rathontech.common.logger.DailyRollingFileAppender
rahonlog4j.appender.out.layout=com.rathontech.common.logger.PatternLayout
rahonlog4j.appender.out.datePattern=.yyyy-MM-dd
rahonlog4j.appender.out.layout.ConversionPattern=%d [%-15.15t] %-5p %-30.30c{1} - %m%n
rahonlog4j.appender.out.file=::webapp.root::/WEB-INF/rtsso2018/log/rathonsso_sp.log
rahonlog4j.appender.out.append=true 