
#HANWHA 

#HW_WSDL_SERVICE_URL = http://htg.circle.hanwha.com/ 
#HW_WSDL_SERVICE_URL = http://hanwha.eagleoffice.co.kr/
HW_WSDL_SERVICE_URL = http://cleverseapi.hanwha-ds.com/
HW_WSDL_SERVICE_URL = http://
HW_COMPANY_ID = 503
HW_SYSTEM_ID = 503AP0028

HW_GROUPWARE_URL = http://cleverseapi.hanwha-ds.com/soap/auth/neoslo/goSloTarget.mvc?authType=2&destination=
#HW_GROUPWARE_URL = http://hanwha.eagleoffice.co.kr/api/branch/common/slo/goSloTarget.mvc?authType=2&destination=




