BASE_ATCH_URL = hyundai
HTML_TITLE = ::: H-Way Standard Management System:::
OLM_SERVER_NAME = H-WAY
OLM_SERVER_URL = https://hway.hec.co.kr/
OLM_MASTER_URL = 

#File Path 
FILE_UPLOAD_BASE_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//base//
FILE_UPLOAD_BOARD_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//board//
FILE_UPLOAD_CHG_SET_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//document//cs//
FILE_UPLOAD_PJT_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//document//
FILE_UPLOAD_ITEM_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//document//
FILE_UPLOAD_IS_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//issue//
FILE_UPLOAD_SR_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//sr//
FILE_UPLOAD_TINY_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//upload//
FILE_UPLOAD_ZIPFILE_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//ROOT//doc//zip//
FILE_UPLOAD_TMP_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//ROOT//doc//tmp//
FILE_EXPORT_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//ROOT//doc//export//
FILE_MULTIMEDIA_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//MULTIMEDIA//
ARIS_XML_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//ROOT//modeling//ARISXML//
MODELING_DIGM_DIR = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//diagram//

HR_IF_PROC = NULL

MODELING_DIGM_IMG_TYPE = png
DEFAULT_LANGUAGE = 1042
DEFAULT_LANG_CODE = KO
DEFAULT_LIST_SCALE = 50
DEFAULT_LIST_PAGE_SCALE = 10
DEFAULT_PASSWRORD = 12345!

#OLM OR ARIS
DEFAULT_MODELER = OLM

#COMPONENT SELECTION
USE_COMP_SR = N
USE_COMP_CR = N
USE_COMP_TASK = N
MULTI_COMPANY = N
USE_CRM = N

#Image Path :: if not Path -> .
IMG_DEFAULT_DIR = images
IMG_DIR_SHORTCUT = menu
IMG_DIR_ARC = arc
IMG_DIR_ITEM = item
IMG_DIR_MODEL_SYMBOL = model
IMG_DIR_POPUP = popup
IMG_DIR_EMPPICTURE = empPicture


#Approval Option
DEF_APPROVAL_SYSTEM = OLM
CSR_APPROVAL_PATH = custom/sf/wf/createWfDoc_CSR
CS_APPROVAL_PATH = custom/sf/wf/createWfDoc_CS
APPROVAL_SYS_URL = https://autowaywf.hyundai.net/Approval/Controls/IntegratedApprovalWebService.asmx?wsdl
APPROVAL_DETAIL_URL =
APPORVAL_MULTI = 

#Email Otion : Y-use, N-not use
USE_EMAIL = Y
EMAIL_TYPE = SMTP
EMAIL_SENDER = hway@hec.co.kr

GW_LINK_URL = https://hway.hec.co.kr//index.do

#SMTP Mail Properties
EMAIL_HOST_IP  = 10.18.1.70
EMAIL_SENDER_NAME = Hway
SMTP_AUTHENTIFICATION = Y
SMTP_ACCOUNT_PWD = A!0hway

# Employee Photo URL
EMP_PHOTO_URL = https://ehr.hec.co.kr/images/emp/HEC/
EMP_PHOTO_ITEM_DISPLAY = Y

# DRM
USE_DRM = SOFTCAMP
DRM_KEY_ID =
DRM_DECODING_FILEPATH = ////10.6.104.249//share_483033ce_0b9b_43a9_9b63_0ba43e7e2902//OLMFILE//document//DRM//

#SAP Link
SAP_HOST = http://shuttle.innoever.net:8000/sap/bc/gui/sap/its/webgui?sap-client=100&sap-language=EN&~transaction=*
SAP_CLIENT = 100
SAP_LANGUAGE = EN

PWD_ENCODING = N
PWD_CHECK = Y
PWD_TEXT_CHECK = Y

CUSTOM_CSS = Y

FILE_FORMAT_WHITE_LIST = XLS,XLSX,HWP,DOC,DOCX,PPT,PPTX,TXT,JPEG,GIF,BMP,JPG,TIF,TIFF,PNG,JPE,CSV,WAV,MP3,ZIP,XLSM,PDF,PPSX,AVI,MP4,ASF,FLV,WMV,GUL,ENC,PPTM,XPS,DWG,HDC,MSG,XDW,EML

#Synap Document Viewer
DOC_VIEWER_URL =

# HTC PROPOSAL URL
PROPOSAL_SERVER_URL =
