#HSO Web Service Client (Create Method Parameter)
CSR_WSDL_SERVICE = SO_OLM_CHANGE
CSR_WSDL_SERVICE_URL = http://ep.hanwha-solarone.com/

#LF SAP Link
LF_SAP_MAX_CONNECT = 100
LF_SAP_CLIENT_NO = 100
LF_SAP_USER_ID = IF_IDMS
LF_SAP_PASSWORD = ifadminidms0
LF_SAP_LANGUAGE = KO
LF_SAP_SERVER_IP = 165.244.231.68
LF_SAP_SYSTEM_NO = 00
LF_SAP_SYSTEM_ID = LFP_POS
LF_SAP_R3_NAME = LFP
LF_SAP_HOST_NAME = LGFLFPDB0
LF_SAP_SERVER_NAME = LGFERP_REAL
LF_SAP_POOL_NAME = SAP_POOL_NAME
LF_SAP_GROUP = LGFLFP

#LF WEP Link
LF_WEB_MDP_URL = http://10.49.8.194:9003/mdp/index.jsp
LF_WEB_PLM_URL = http://10.49.8.220:8080/enovia/servlet/lfcssologin		
				
#HANWHA 
HW_WSDL_SERVICE_URL = http://htg.circle.hanwha.com/ 
#HW_WSDL_SERVICE_URL = http://hanwha.eagleoffice.co.kr/
HW_COMPANY_ID = 503
HW_SYSTEM_ID = 503AP0028
HW_ADRM_WSDL_SERVICE_URL = http://96.97.23.66:8080/
HW_ADRM_WS_KEY = A1234 
HW_ADRM_SERVICE_CODE =  PRIME_001
HW_GROUPWARE_URL = http://htg.circle.hanwha.com/neo/branch/common/slo/goSloTarget.mvc?authType=2&destination=


#SKHynix Link
SK_MPM_URL = http://heps.skhynix.com/sso/agentless/agentless_redirect.jsp?initpage=http://mpm.skhynix.com/indexSK.jsp
#DEV  url=http://ssodev.skhynix.com/sso/agentless/agentless_redirect.jsp?initpage=http://mpmdev.skhynix.com/indexSK.jsp
# http://sso.skhynix.com/sso/agentless/agentless_redirect.jsp?initpage=http://mpm.skhynix.com/indexSK.jsp
SK_ACC_RJC_URL = http://ssodev.skhynix.com/common/OnAccessReject.htm 
SK_LOGOUT_URL = http://ssodev.skhynix.com/common/logout.asp?TARGET=http://10.156.20.117:8080/sso_login.jsp
FILE_UPLOAD_CTS_DIR = C://OLMFILE//cts//

#CJ Val

CJ_SSO_URL = http://dev.cjwise.net
#QA CJ_SSO_URL = http://qa.cjwise.net
#Run CJ_SSO_URL = http://cjwise.net
EMP_PHOTO_URL = https://ep.halla.com

#HSO
HSO_DOMAIN = "solarone.com";
HSO_LDAPHOST = "ldap://172.16.3.19";	


#DAELIM
IEP_POP_URL = http://portal.daelimplant.com/ProjectPortal/UserControls/BestPractice/BestPracticeDetailView.aspx


